#!/usr/bin/env bash
# Install nginx commands for Sandbox

sudo apt-get -y upadte
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
sudo echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
