#!/usr/bin/env bash
# Installing nginx

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
sudo echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html

sudo touch /var/www/html/error404.html
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/error404.html

search_string="^\tlocation / {"
replace_string="\terror_page 404 /error404.html;\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation / {"
sed -i "s@${search_string}@${replace_string}@" /etc/nginx/sites-available/default

sudo service nginx restart