#!/usr/bin/env bash
# Install nginx commands for Sandbox

sudo apt-get -y upadte
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
sudo echo "Holberton School for the win!" | sudo tee /var/www/html/index.nginx-debian.html

sudo touch /var/www/html/error404.html
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/error404.html

searchString="^\tlocation / {"
replaceString="\terror_page 404 /error404.html;\n\n\tlocation \
/redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\
\n\n\tlocation / {"

sudo sed -i "s@${searchString}@${replaceString}@" /etc/nginx/sites-available/default

sudo service nginx restart
