#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

sudo apt-get -y update
sudo apt-get -y upgrade

sudo apt-get -y install haproxy

str="\nfrontend http_web\n\tbind *:80\n\tstats uri /haproxy?stats\n\tdefault_backend custom_backend\n\n\tbackend custom_backend\n\tbalance roundrobin\n\tserver rkbrian 34.227.228.210:80 check\n\tserver rkbrian02 3.80.186.246:80 check"

sudo echo -e $str | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
