#!/usr/bin/env bash
# Kill to stop the bash script that displays To infinity and beyond indefinitely.

pgrep "100-process_and_pid_file" > /var/run/holbertonscript.pid
# _term(){echo "I hate the kill command"rm /var/run/holbertonscript.pidkill -9 "$("100-process_and_pid_file")"}
trap 'echo "I hate the kill command"; rm /var/run/holbertonscript.pid' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/holbertonscript.pid' SIGQUIT
while :; do echo "To infinity and beyond"; sleep 2; done
