#!/usr/bin/env bash
# Bash script that displays a list of currently running processes.

ps -auxf | less
# note to myself: -a for all process; -u for including other users; -x for no ctrling ttys; -f for full format listing
