#!/usr/bin/env bash
# Kill to stop the bash script that displays To infinity and beyond indefinitely.

trap 'echo "I hate the kill command"; rm /var/run/holbertonscript.pid; exit' SIGTERM
# trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/holbertonscript.pid; exit' SIGQUIT

sudo touch /var/run/holbertonscript.pid
echo $BASHPID > /var/run/holbertonscript.pid
while :; do echo "To infinity and beyond"; sleep 2; done
