#!/usr/bin/env bash
# This script is displaying the content of the file /etc/passwd with trimmed information, only using while loop
# display info: username, user id, home directory path for the user
file_to_read=/etc/passwd
while read -r text_line; do
    echo $text_line | cut -d ":" -f 1,3,6
done < "$file_to_read"
