#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times, use while-loop only
# 4th line is replaced with "bad luck", 8th line is replaced with "good luck"
i=1; while [ $i -le 10 ]
do if [[ $i == 4 ]]; then echo "bad luck"
    elif [[ $i == 8 ]]; then echo "good luck"
    else echo "Holberton School"; fi
    ((i++))
done
