#!/usr/bin/env bash
# This script is giving information about the holbertonschool file
myfile="holbertonschool"; if [ -e $myfile ]; then echo "$myfile file exists";
    if [ -s $myfile ]; then echo "$myfile file is not empty"; else echo "$myfile file is empty"; fi
    if [ -f $myfile ]; then echo "$myfile is a regular file"; fi
else echo "$myfile file does not exist"; fi
